// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IconAccessibility: typeof import('~icons/ic/on-accessibility')['default']
    IconAccountBox: typeof import('~icons/ic/on-account-box')['default']
    MdiAccount: typeof import('~icons/mdi/account')['default']
    MdiAccountCircle: typeof import('~icons/mdi/account-circle')['default']
    MdiAccountFilterOutline: typeof import('~icons/mdi/account-filter-outline')['default']
  }
}

export { }
